language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer install --dev

branches:
  only:
    master

script:
  - (cd test ; ../vendor/bin/phpunit -c phpunit.xml)
  - php -n -d memory_limit=768M ./vendor/bin/php-cs-fixer fix --dry-run -vv --rules=@PSR2 .

fast_finish: true

allow_failures:
  - php: nightly
