language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

branches:
  only:
    master

script:
  - php -n -d memory_limit=768M ./vendor/bin/php-cs-fixer fix --dry-run -vv --rules=@PSR2 .
  - (cd test ; ../vendor/bin/phpunit -c phpunit.xml --coverage-clover=../clover.xml)

after_success:
  - cd ..
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml

fast_finish: true

matrix:
  allow_failures:
    - php: nightly
