sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS=""
    - COMPOSER_DISCARD_CHANGES=1

stages:
  - coding style
  - static code analysis
  - test
  - test with coverage

install:
  - travis_retry composer update --no-interaction --prefer-stable $COMPOSER_ARGS

branches:
  only:
    master

script:
  - ./vendor/bin/phpunit --no-coverage --colors

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.3
    - php: 7.4
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.4
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs --prefer-lowest"
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs"

    - stage: coding style
      php: 7.2
      script: ./vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.2
      script:
        - composer phpstan
        - composer psalm

    - stage: test with coverage
      php: 7.2
      script: ./vendor/bin/phpunit --colors --coverage-clover=./clover.xml
      after_success: bash <(curl -s https://codecov.io/bash) -f ./clover.xml
