sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS=""

stages:
  - coding style
  - static code analysis
  - test
  - test with coverage

install:
  - travis_retry composer install --no-interaction --prefer-stable $COMPOSER_ARGS

branches:
  only:
    master

script:
  - ./vendor/bin/phpunit --no-coverage --colors

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.6
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 5.6
    - php: 7
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7
    - php: 7.1
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.2
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs --prefer-lowest"
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs"

    - stage: coding style
      php: 7.2
      script: php -n -d memory_limit=768M ./vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.2
      script:
        - vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src
        - vendor/bin/psalm --show-info=false

    - stage: test with coverage
      php: 7.2
      script: ./vendor/bin/phpunit --colors --coverage-clover=./clover.xml
      after_success: bash <(curl -s https://codecov.io/bash) -f ./clover.xml
