sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

branches:
  only:
    master

script:
  - php -n -d memory_limit=768M ./vendor/bin/php-cs-fixer fix --dry-run -vv
  - ./vendor/bin/phpunit --coverage-clover=./clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
